module.exports = [
  {'id': 0, 'title': 'activity-0', 'type': 'activity', 'activityIndex': 0},
  {'id': 1, 'title': 'activity-1', 'type': 'activity', 'activityIndex': 1},
  {'id': 2, 'title': 'activity-2', 'type': 'activity', 'activityIndex': 2},
  {'id': 6, 'title': 'task-6', 'type': 'task', 'activityIndex': 0, 'taskIndex': 0},
  {'id': 9, 'title': 'task-9', 'type': 'task', 'activityIndex': 0, 'taskIndex': 1},
  {'id': 3, 'title': 'task-3', 'type': 'task', 'activityIndex': 0, 'taskIndex': 2},
  {'id': 12, 'title': 'subtask-12', 'type': 'subtask', 'activityIndex': 0, 'taskIndex': 0, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'todo'},
  {'id': 18, 'title': 'subtask-18', 'type': 'subtask', 'activityIndex': 0, 'taskIndex': 1, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'doing'},
  {'id': 24, 'title': 'subtask-24', 'type': 'subtask', 'activityIndex': 0, 'taskIndex': 2, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'todo'},
  {'id': 21, 'title': 'subtask-21', 'type': 'subtask', 'activityIndex': 0, 'taskIndex': 0, 'releaseIndex': 1, 'subtaskIndex': 0, 'label': 'ready'},
  {'id': 15, 'title': 'subtask-15', 'type': 'subtask', 'activityIndex': 0, 'taskIndex': 1, 'releaseIndex': 1, 'subtaskIndex': 0, 'label': 'done'},
  {'id': 27, 'title': 'subtask-27', 'type': 'subtask', 'activityIndex': 0, 'taskIndex': 1, 'releaseIndex': 1, 'subtaskIndex': 1, 'label': 'done'},
  {'id': 4, 'title': 'task-4', 'type': 'task', 'activityIndex': 1, 'taskIndex': 0},
  {'id': 7, 'title': 'task-7', 'type': 'task', 'activityIndex': 1, 'taskIndex': 1},
  {'id': 25, 'title': 'subtask-25', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 1, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'ready'},
  {'id': 16, 'title': 'subtask-16', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 0, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'todo'},
  {'id': 10, 'title': 'subtask-10', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 0, 'releaseIndex': 0, 'subtaskIndex': 1, 'label': 'doing'},
  {'id': 13, 'title': 'subtask-13', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 1, 'releaseIndex': 1, 'subtaskIndex': 0, 'label': 'ready'},
  {'id': 19, 'title': 'subtask-19', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 1, 'releaseIndex': 1, 'subtaskIndex': 1, 'label': 'done'},
  {'id': 22, 'title': 'subtask-22', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 0, 'releaseIndex': 1, 'subtaskIndex': 0, 'label': 'doing'},
  {'id': 28, 'title': 'subtask-28', 'type': 'subtask', 'activityIndex': 1, 'taskIndex': 0, 'releaseIndex': 2, 'subtaskIndex': 0, 'label': 'todo'},
  {'id': 8, 'title': 'task-8', 'type': 'task', 'activityIndex': 2, 'taskIndex': 0},
  {'id': 5, 'title': 'task-5', 'type': 'task', 'activityIndex': 2, 'taskIndex': 1},
  {'id': 20, 'title': 'subtask-20', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 0, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'todo'},
  {'id': 14, 'title': 'subtask-14', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 0, 'releaseIndex': 1, 'subtaskIndex': 0, 'label': 'doing'},
  {'id': 26, 'title': 'subtask-26', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 0, 'releaseIndex': 2, 'subtaskIndex': 0, 'label': 'doing'},
  {'id': 29, 'title': 'subtask-29', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 1, 'releaseIndex': 0, 'subtaskIndex': 0, 'label': 'ready'},
  {'id': 23, 'title': 'subtask-23', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 1, 'releaseIndex': 1, 'subtaskIndex': 0, 'label': 'done'},
  {'id': 17, 'title': 'subtask-17', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 1, 'releaseIndex': 2, 'subtaskIndex': 0, 'label': 'ready'},
  {'id': 11, 'title': 'subtask-11', 'type': 'subtask', 'activityIndex': 2, 'taskIndex': 1, 'releaseIndex': 2, 'subtaskIndex': 1, 'label': 'done'}
];
